### ISSUE TITLE
JVFloatLabeledTextView placeholder text appears in 2 line when it is used in tableviewCell. 

### ISSUE THREAD

**Issue by cashish** [jverdi/JVFloatLabeledTextField#101]
JVFloatLabeledTextView placeholder text appears in 2 line when it is used in tableviewCell

Initially it works fine. when we remove the text from textview it becomes 2 lines, and after that never resets itself.
PFA  of issue below :

![text copy](https://cloud.githubusercontent.com/assets/3477870/7897318/a00ac21e-06f5-11e5-8b8d-221a1fee3e99.png)

**Comment by jverdi** [comment]
I cannot reproduce. Please provide example code to demonstrate the issue if it still occurs.
