### ISSUE TITLE
Question: noob question: how to add this to an xcode project

### ISSUE THREAD

**Issue by mschipperheyn** [jverdi/JVFloatLabeledTextField#102]
I'm new to ios development coming from java. And I just can't find any good reference information on how to simply use this component in an xcode project?

**Comment by tailec** [comment]
1. Get cocoapods (easiest way) or drag and drop files to your project. Useful links:
[cocoapods.org](cocoapods.org)
[route85 tutorial](https://www.youtube.com/watch?v=iEAjvNRdZa0)
2. If you're adding your views programmatically then do the same with JVFloatLabeledTextField/TextView. If you're using storyboards then drag and drop UITextField/UITextView to your scene and set custom class as JVFloatLabeledTextField/JVFloatLabeledTextView.

**Comment by danyalaytekin** [comment]
Copy and paste to documentation :)

**Comment by jverdi** [comment]
Thanks, I've added some basic getting started instructions to the README, which include dyed for use with Cocoapods as well as Carthage.
