### ISSUE TITLE
Cocoa Pods using 1.0.2

### ISSUE THREAD

**Issue by hipwelljo** [jverdi/JVFloatLabeledTextField#105]
Despite the fact the latest version shows 1.1.0 next to pods, when I run pod update/install it uses version 1.0.2.

**Comment by jverdi** [comment]
Hi @hipwelljo - that's not my experience. Is it still grabbing 1.0.2 for you? It may have just been a caching issue. 

If it's still occurring, could you share the line from your Podfile for JVFloatLabeledTextField?

**Comment by hipwelljo** [comment]
I can confirm this is still the case. My podfile contains: pod 'JVFloatLabeledTextField'
pod update logs Using JVFloatLabeledTextField (1.0.2)
I tried pod 'JVFloatLabeledTextField' '~> 1.1.0' but it failed with error: 
[!] Unable to satisfy the following requirements:
- `JVFloatLabeledTextField (~> 1.1.0)` required by `Podfile`

**Comment by Zhukn1** [comment]
try running `pod setup` as it's probably a bug with updating the master repo.

**Comment by hipwelljo** [comment]
Thanks @Zhukn1, this solved it:
`sudo rm -fr ~/Library/Caches/CocoaPods/ 
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod update`

**Comment by Zhukn1** [comment]
👍🏻
