### ISSUE TITLE
iOS 9 and JVFloatLabeledTextField

### ISSUE THREAD

**Issue by tomvanzummeren** [jverdi/JVFloatLabeledTextField#106]
Hello, I am not sure if it is related to iOS 9 but when I try out the JVFloatLabeledTextField in my project, the text jumps down a bit when I start editing the text field.

<img width="183" alt="simulator - - screen shot 11 july 2015 at 15 31" src="https://cloud.githubusercontent.com/assets/188839/8633896/e7feb8b6-27e1-11e5-8f46-56140f61c992.png">
<img width="170" alt="safari - github com - - screen shot 11 july 2015 at 15 31" src="https://cloud.githubusercontent.com/assets/188839/8633897/ea05a714-27e1-11e5-89f6-9eb87c515a47.png">

**Comment by jverdi** [comment]
@tomvanzummeren have you set ```keepBaseline``` to YES? The default behavior is as you describe, and ```keepBaseline``` provides a way to keep the value in the same position as the placeholder

**Comment by tomvanzummeren** [comment]
Oh, yes that's it. Didn't know that. Thanks!

**Comment by mohitAppRinger** [comment]
I tried the above code but in my case the frame of _UITextFieldCanvasView is different...Please check out the screenshot below.

<img width="1024" alt="Screenshot 2020-02-19 at 1 15 04 AM" src="https://user-images.githubusercontent.com/56431665/74772129-6bd68300-52b5-11ea-83bd-c4630f2109ad.png">

I don't know why this is happening.
