### ISSUE TITLE
Placeholder text color

### ISSUE THREAD

**Issue by rayesh** [jverdi/JVFloatLabeledTextField#107]
Is it possible to set the color of the placeholder text? I see that [SSTextField](https://github.com/samsoffes/sstoolkit/blob/master/SSToolkit/SSTextField.h) does that through an overridden `drawPlaceholderInRect`.

**Comment by jverdi** [comment]
@rayesh you can the ```attributedPlaceholder``` on text fields to change placeholder colors

**Comment by rayesh** [comment]
Thank you. I had missed it.
