### ISSUE TITLE
Floating label should in full width when floatingLabelShouldLockToTop=YES

### ISSUE THREAD

**Issue by anandmahajan** [jverdi/JVFloatLabeledTextField#114]
here is my code

    textView.font = FONT_SANS_REGULAR_H1;
    textView.placeholderTextColor = UICOLOR_ASKQUESTION;
    textView.floatingLabelActiveTextColor=UICOLOR_NAVIGATION_BG;
    textView.floatingLabelTextColor=UICOLOR_NAVIGATION_BG;
    textView.floatingLabelFont = FONT_SANS_REGULAR_H0;
    
    textView.backgroundColor=[UIColor whiteColor];
    textView.floatingLabelShouldLockToTop=YES;
    
    textView.floatingLabelYPadding=3;

When I set textView.floatingLabelYPadding=3 ...also gap from top in floating label when I scroll textview

Please see attachment.
![screen shot 2015-10-31 at 3 30 13 pm](https://cloud.githubusercontent.com/assets/1219379/10862954/58ac7518-7fe3-11e5-83d6-0ca6a90ea90f.png)

Any suggestion.?

Thanks

**Comment by jverdi** [comment]
hi @anandmahajan - does the PR that was just pulled in here help? https://github.com/jverdi/JVFloatLabeledTextField/pull/112
