### ISSUE TITLE
adjustsFontSizeToFitWidth Does Not Work

### ISSUE THREAD

**Issue by SolomonBier** [jverdi/JVFloatLabeledTextField#121]
Is it possible to use `adjustsFontSizeToFitWidth` by setting the `textfield` property? Nothing happens when I do so

**Comment by pabloruan0710** [comment]
help??

**Comment by jverdi** [comment]
The behavior for `adjustsFontSizeToFitWidth` when using JVFloatLabeledTextField appears to be the same as with UITextField as far as I can tell. Can you provide a counter example demonstrating the problem?
