### ISSUE TITLE
Text Field Alignment Issues?

### ISSUE THREAD

**Issue by CMoebius** [jverdi/JVFloatLabeledTextField#123]
We are having an issue where we are using this class in a tableview cell. During text entry, the vertical spacing is different from the field when it is not being edited.

As shown in the screen shot, you can see a difference when editing the text and not. 

![screen shot 2016-01-28 at 9 53 04 am](https://cloud.githubusercontent.com/assets/528908/12647813/1ec26760-c5a5-11e5-996d-2783e2e88630.png)

Thanks in advance.

**Comment by jverdi** [comment]
@CMoebius have you tried setting the keepBaseline property?

**Comment by CMoebius** [comment]
Yes, and all that did was drop the text field to the bottom of the table view cell when editing.

**Comment by jverdi** [comment]
I think that's what you would want to do in order to make sure that editing vs. not editing are at the same position. Then, you can use other means to pad around the text field so that it is positioned how you'd like.
