### ISSUE TITLE
Problem with transparent background and border style

### ISSUE THREAD

**Issue by burakkilic** [jverdi/JVFloatLabeledTextField#124]
Hi;

If I change the border style to None, I cannot see the placeholder. 

![screen shot 2016-02-01 at 10 28 06](https://cloud.githubusercontent.com/assets/123382/12712119/81ac995a-c8ce-11e5-9c10-3c0e7ebc9fd2.png)

What should I do?

**Comment by jverdi** [comment]
@burakkilic could you be more specific about your configuration? I'm guessing this screenshot is showing multiple text fields and only the first is visible? And, I imagine you've already tried changing the placeholder color?
