### ISSUE TITLE
Custom Font with JVFloatLabeledTextView in IB Not Working

### ISSUE THREAD

**Issue by kylebshr** [jverdi/JVFloatLabeledTextField#126]
Hello, 

I'm trying to use the float labels in a basic form, and most of them are JVFloatLabeledTextField, which works great. However, one of them is a JVFloatLabeledTextView, and the custom font I'm setting in IB isn't being respected when the app is run. It actually shows the correct font in IB, just not in the running app:

IB: 
<img width="273" alt="screen shot 2016-02-05 at 12 51 15 pm" src="https://cloud.githubusercontent.com/assets/3526783/12854334/2daa4726-cc07-11e5-8e71-2797d5ea1cef.png">

App:
<img width="273" alt="screen shot 2016-02-05 at 12 51 15 pm" src= "https://cloud.githubusercontent.com/assets/3526783/12854368/652c437a-cc07-11e5-9dc4-7e4b13c90693.png">

Is there potentially something I'm doing wrong, or is this a known issue?

Thanks for the help!

**Comment by jverdi** [comment]
Hi @kylebshr - I was unable to reproduce this, but I just pushed a XIB configuration for testing this out: https://github.com/jverdi/JVFloatLabeledTextField/commit/e457401edd2fe0796f6105591351858510950604

Both the text field and the text view in that setup use the Georgia font in IB.
Can you take a look and see how it differs from your setup? Thanks!
