### ISSUE TITLE
Placeholder keeps on growing in size

### ISSUE THREAD

**Issue by allanmacatingrao** [jverdi/JVFloatLabeledTextField#129]
Steps to recreate:
1. Type in a word
2. Delete the word completely 
3. repeat 1-2 

Actual: The placeholder text keeps on growing when repeating steps 1-2 
Expected: The placeholder text should keep its original size after deleting the input word

**Comment by jverdi** [comment]
Hi @allanmacatingrao, can you describe your configuration and any customizations? Are you using interface builder?

**Comment by allanmacatingrao** [comment]
Im using interface builder. I added a text field and set the class to `JVFloatLabeledTextField`.

**Comment by jverdi** [comment]
Closing this issue as it has been a while (sorry). I don't think I had enough context to reproduce the issue here. If its still a concern, please reopen and provide some example code and I'll be happy to look into it. Thanks!
