### ISSUE TITLE
Delegates not working

### ISSUE THREAD

**Issue by galileoguzman** [jverdi/JVFloatLabeledTextField#130]
Hello guys,

I'm developing an IOS mobile appplication with objective-c and I'm using JVFloatLabeledTextField and JVFloatLabeledTextView. I have problem detecting return key pressed event. I did the next step:
1 - On Interface builder asign the class JVFloatLabeledTextField and JVFloatLabeledTextView
2 - On interfacebuilder at Inspector connections I linked the textfields delegates with controller owner
3 - On header file I wrote delegates to use on class <UITextFieldDelegate...>
4 - And I put the method delegate 
 - (BOOL) textFieldShouldReturn:(JVFloatLabeledTextField *)textField{}
 - (BOOL) textFieldShouldReturn:(UITextField *)textField

But is not working, the method not detect the event. Somebody knows the solution?

**Comment by galileoguzman** [comment]
I solved this issue, thank you!!!

**Comment by avselva** [comment]
how did you solved?

**Comment by Bhawin21** [comment]
how ?

**Comment by OMGHaveFun** [comment]
@SelvaRaj08 @Bhawin21 

@property (weak, nonatomic) IBOutlet JVFloatLabeledTextField *regionTextField;
...
- (IBAction)textFieldEditingChanged:(JVFloatLabeledTextField *)sender {
...
