### ISSUE TITLE
Can I show a bottom border when text field get focus?

### ISSUE THREAD

**Issue by hemangshah** [jverdi/JVFloatLabeledTextField#134]
Can I show a bottom border when text field get focus?

Please see the screenshot attached.

![screen shot 2016-05-15 at 10 32 32 pm](https://cloud.githubusercontent.com/assets/3313412/15275566/fd1a8b72-1aec-11e6-95b1-91ba7c87653a.png)

Reference: **First Name**

Oh and yes, thanks for the awesome library! 👍

**Comment by Zhukn1** [comment]
Hi @hemangshah, you can check out my fork: https://github.com/Zhukn1/JVFloatLabeledTextField

I've forked specifically for this option. `hasUnderline = true`

**Comment by Zhukn1** [comment]
also there is a neat lock icon appearing if the textfield is disabled 😀

If you have any questions, feel free to ask.

**Comment by hemangshah** [comment]
@Zhukn1 , thanks for quick reply. 👍 

May I ask why @jverdi is not pulling this changes to his git?

**Comment by Zhukn1** [comment]
@hemangshah, I've gone through this with @jverdi here: https://github.com/jverdi/JVFloatLabeledTextField/pull/76

I respect the repo owner's opinion and that's why never insisted on merging the changes. You can always use my fork, it won't disappear anywhere or you can for my fork 👍🏻

**Comment by hemangshah** [comment]
@Zhukn1 , thanks 👍
