### ISSUE TITLE
How can I change the position of the textFields?

### ISSUE THREAD

**Issue by Kouga777** [jverdi/JVFloatLabeledTextField#135]
Hi,
First I want to thank you for this really awesome library
I just wanted to know where to change the position of the textFields?
For example I wanted the textFields to show at lower position, I have the solution for preventing keyboard from hiding the textFields.
Thanks again..

**Comment by jverdi** [comment]
You can place the text field wherever you like by adjusting the component's frame. There are also options like `floatingLabelYPadding`, `placeholderYPadding`, and `keepBaseline` to adjust how the components views relate to each other. Hope that helps
