### ISSUE TITLE
JVFloatLabeledTextView has a bug

### ISSUE THREAD

**Issue by iceman201** [jverdi/JVFloatLabeledTextField#137]
It's normal when doesnt scroll the view.
![image](https://cloud.githubusercontent.com/assets/5027957/15574654/dfd35210-23a2-11e6-86ee-dbb188ed9ec3.png)

However, if I do scroll, the view will looks like this
![image](https://cloud.githubusercontent.com/assets/5027957/15574702/09e0414e-23a3-11e6-98ea-e2a06db0b925.png)

**Comment by jverdi** [comment]
Check out the docs for `floatingLabelShouldLockToTop`. You'll want to set that to `YES`

**Comment by iceman201** [comment]
thanks man
