### ISSUE TITLE
The float label's text seems to be not as bold as the screenshot in README

### ISSUE THREAD

**Issue by Sweeper777** [jverdi/JVFloatLabeledTextField#138]
I am doing this in Interface Builder in Xcode 7.3.

I set the following attributes of a `JVFloatLabeledTextField`

- Floating Label Active Color: some color
- Border Style: None

When I run the app, I see that the float label's text is not as bold as the screenshot in the README file:

<img width="311" alt="screen shot 2016-06-01 at 2 36 09 pm" src="https://cloud.githubusercontent.com/assets/13585047/15700495/af7ab41a-2806-11e6-90b0-a317ed5e9b79.png">

verses

<img width="498" alt="screen shot 2016-06-01 at 2 39 47 pm" src="https://cloud.githubusercontent.com/assets/13585047/15700504/bffcc936-2806-11e6-9a5d-adcf0befea68.png">

How can I make it bold? If you can show me how to do this in Swift, that would be fantastic. But Objective-C is also fine.

**Comment by jverdi** [comment]
There is a property called `floatingLabelFont` for making changes to the font of `JVFloatLabeledTextField` floating label (in blue in the screenshot). Hope that helps.
