### ISSUE TITLE
How to set text??

### ISSUE THREAD

**Issue by ketan2409** [jverdi/JVFloatLabeledTextField#140]
I want to set some text in this text field, how do i do that.I tried following code but it's not working.

JVFloatLabeledTextField *myTextField = [JVFloatLabeledTextField alloc] init];
myTextField.text = myString;

**Comment by szweier** [comment]
`myTextField.text` should work if you're trying to fill in the textfield.
`myTextField.placeholder` would be if you wanted temporary placeholder text that you could type over.
placeholder is also what turns into the float labeled field when you type text if you didn't use 
`setPlaceholder:placeholder floatingTitle:floatTitle`

**Comment by ketan2409** [comment]
@szweier  Thanks

**Comment by szweier** [comment]
No problem.
