### ISSUE TITLE
adjustsFontSizeToFitWidth seems to be causing memory issues

### ISSUE THREAD

**Issue by Shweesome** [jverdi/JVFloatLabeledTextField#147]
I have tried to set my text field's adjustsFontSizeToFitWidth property to YES. However, every time I run my app, it just goes crazy with memory usage. When I remove the property, it is fine.

**Comment by jverdi** [comment]
I don't know of any reason offhand why that property would have any effects on memory usage. If you are still experiencing this and can provide more context, or an example project, please reopen the issue and I will be happy to look into it.
