### ISSUE TITLE
Why it is like that.. 

### ISSUE THREAD

**Issue by narekam** [jverdi/JVFloatLabeledTextField#148]
I initialize JVFloatLabeledTextField through Storyboard and have in viewDidLoad smth like this [self.phoneNumberTextField setText:@"444366151"]; When screen showed up I see Pic1, and only after tapping on textfield it showed up normal like in Pic2. I just want to see proper layout from very begin. Please help!
![1](https://cloud.githubusercontent.com/assets/13750851/19696092/d8a8dcd2-9af6-11e6-890d-8ba6500bf5d7.jpeg)
![2](https://cloud.githubusercontent.com/assets/13750851/19696093/d8c74e38-9af6-11e6-980f-a5e57d55d04d.jpg)

**Comment by MinhNguyenVan** [comment]
You have to add this line after set text for textfield:

[textField layoutSubviews];

**Comment by narekam** [comment]
I've figured it out already, thanks! And yes, that works!
