### ISSUE TITLE
Impossible to set top padding in JVFloatLabeledTextView between label and input text

### ISSUE THREAD

**Issue by stefanomondino** [jverdi/JVFloatLabeledTextField#152]
Usually i use the `textContainerInset` property in UITextViews when I'm required to implement padding around the input control.
I found out it's impossible to set the top padding, since it's overwritten to allow correct placement of the floating label.

I believe it would be helpful to change the visibility of this

`@property (nonatomic) CGFloat startingTextContainerInsetTop;`

by making it public

**Comment by jverdi** [comment]
Fixed via #153 (thanks!)
