### ISSUE TITLE
Distance to Float Label Different Between Text Field and Text View

### ISSUE THREAD

**Issue by pschneider** [jverdi/JVFloatLabeledTextField#155]
Hi,

while implementing your library I noticed that the Text Field and Text View have different distances to the floating label. I tried fixing it using padding on the Text Field but unfortunately I couldn't make it look like the Text View as the text input renders incorrectly when using a big negative padding. 
The both fields do not have any special configuration just some auto layout constraints.

I already tried setting the content inset and edge inset for the text view to zero but it didn't work.

Is this a bug or do you have any solution how I can make both look like the same? (Preferred the distance like the Text View)

Thanks!

Attached Screenshot:

![simulator_screen_shot_jan_13 _2017 _10 34 08_am2](https://cloud.githubusercontent.com/assets/846617/21957554/ea04bcf8-da98-11e6-97cf-9d64cf1abf03.jpg)

**Comment by jverdi** [comment]
I believe the text field spacing is dependent on your text field's height. You could try modifying its height, or playing with the text view's `floatingLabelYPadding`.
