### ISSUE TITLE
Manually display floating text

### ISSUE THREAD

**Issue by eggnima** [jverdi/JVFloatLabeledTextField#161]
Is there a way that we can manually show the floating text label with animation, as opposed to having to wait for user keying in text?

Thanks!

**Comment by jverdi** [comment]
There are methods to do it, but they aren't exposed in the header file:
`- (void)showFloatingLabel:(BOOL)animated`
`- (void)hideFloatingLabel:(BOOL)animated`

@eggnima Can I ask what the use case is? I'm not sure it's a common enough need...

**Comment by qsdnino** [comment]
This should be allowed to set manually text by code and animate at that moment. Thanks
