### ISSUE TITLE
Small improvement suggested

### ISSUE THREAD

**Issue by FrizzTheSnail** [jverdi/JVFloatLabeledTextField#162]
Hi, I needed to set the placeholder text as an attributed string (using letter spacing).
It works using _setAttributedPlaceholder_ but the floating string doesn't get the attributed settings (eg: spacing :) )
So I made a small improvement:

1.  Added the function: setFloatingLabelAttributedText
```
- (void)setFloatingLabelAttributedText:(NSString *)attributedText
{
    NSMutableAttributedString* fixedAttributedText = [attributedText mutableCopy];
    [fixedAttributedText addAttribute:NSFontAttributeName value:_floatingLabelFont range:NSMakeRange(0, attributedText.length)];
    _floatingLabel.attributedText = fixedAttributedText;
    [self setNeedsLayout];
}
```

2. Replaced _setFloatingLabelText_ with _setFloatingLabelAttributedText_ all around. It worked nicely!

Please find attached the modified file:
[JVFloatLabeledTextField.m.txt](https://github.com/jverdi/JVFloatLabeledTextField/files/839146/JVFloatLabeledTextField.m.txt)

Regards, David

**Comment by AntonReality** [comment]
@FrizzTheSnail Already discussed how to fix thus :)

https://github.com/jverdi/JVFloatLabeledTextField/issues/157

**Comment by jverdi** [comment]
Closing based on #157. Please let me know if it doesnt solve the issue for you @FrizzTheSnail

**Comment by kientux** [comment]
I think what he means is the attributed text of floating label. In source code it's never set, so basically this library does not support floating attributed text.
