### ISSUE TITLE
changing secureTextEntry results in changing font in iOS < 10

### ISSUE THREAD

**Issue by catchakos** [jverdi/JVFloatLabeledTextField#163]
When setting the secureTextEntry property of JVFloatLabeledTextField on and off (password-like textField) and using some custom font it eventually gets overriden by the system font. Happens in iOS 8, iOS 9, not in iOS 10.

Test project with single JVFloatLabeledTextField and button changing its secureTextEntry property:
https://github.com/catchakos/JVFloatLabeledTextField_secureTextEntry.git

**Comment by catchakos** [comment]
seems to be a bug in UITextField, fixed in iOS 10. 
Any possible solutions?

**Comment by jelteliekens** [comment]
@catchakos Did you find any solution for this? I'm having the same issue.
