### ISSUE TITLE
Couldn't change Placeholder color

### ISSUE THREAD

**Issue by axiom88-guru** [jverdi/JVFloatLabeledTextField#169]
Thanks for the great library .
I am currently having one issue because I can't change placeholder color . I changed the placeholder color using interface builder (Xcode8.3.2) , but it doesn't have any effect on the textfield. Placeholder text is still gray color. 
Any idea would be appreciated . 
Regards

**Comment by XRadevFRT** [comment]
Same issue here.

**Comment by XRadevFRT** [comment]
I fixed it. The problem was in JVFloatLabeledTextField.m -> line 357 : 
**_floatingLabel.textColor = (firstResponder && self.text && self.text.length > 0 ?
                                self.labelActiveColor : self.floatingLabelTextColor);**
I just switched **self.labelActiveColor** and **self.floatingLabelTextColor** places.
Hope that helped.

**Comment by jverdi** [comment]
As mentioned in #150, I just released a 1.2.0 version of the cocoapod. Hopefully that solves this issue. Let me know if not.
