### ISSUE TITLE
IB Designables Failed to render and update auto layout status for UIViewController

### ISSUE THREAD

**Issue by Balagurunath** [jverdi/JVFloatLabeledTextField#175]
Hi,
Need one help from anyone.

Whenever I'm adding a JVFloatLabeledTextField, I'm getting the following error

IB Designables Failed to render and update auto layout status for UIViewController 

Please help to resolve this issue

**Comment by arifmc** [comment]
Having the same issue, any solution?

**Comment by swanback** [comment]
I solved this problem (thanks SO) by adding "use_frameworks!" in my Podfile.
