### ISSUE TITLE
iOS11: intrinsicContentSize height changes while typing, leads to flickering

### ISSUE THREAD

**Issue by Argent** [jverdi/JVFloatLabeledTextField#182]
On iOS 11, if you don't constrain the textField to a fixed height, the intrinsicContentSize's height will change while typing.

See attached video:
![out](https://user-images.githubusercontent.com/717301/32537129-affff000-c461-11e7-8e42-9e50dcaac164.gif)

On iOS 10 and earlier this was working fine.

Tested with latest version 1.2.1

**Comment by nrgbodya** [comment]
Still happening in 1.2.3, I just created a bug fix 👍🏼 CGRectIntegral func seems to cause troubles. I also have written a test that makes sure this bug never bother us again.

**Comment by jverdi** [comment]
merged!
