### ISSUE TITLE
Warnings - This block declaration is not a prototype

### ISSUE THREAD

**Issue by anirudhamahale** [jverdi/JVFloatLabeledTextField#184]
I am getting this strange warning "This block declaration is not a prototype" in version 1.2.1, using the Swift 4 and Xcode 9.2 (9C40b). 
Getting it at 4 places:
1) JVFloatLabeledTextField.m line number 133, 155
2) JVFloatLabeledTextView.m line number 238, 265

![screen shot 2017-12-13 at 3 46 45 pm](https://user-images.githubusercontent.com/16848003/33934105-db428ac0-e01d-11e7-987b-b678cf7daf04.png)
-

**Comment by biren9** [comment]
This is a change of the Xcode 9 compiler. You have to give a return type such void

```
void (^showBlock)(void) = ^{
...
};
```

[https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9](url)

**Comment by jverdi** [comment]
This has since been fixed.
