### ISSUE TITLE
How to use JVFloatLabeledTextField in objective c ? 

### ISSUE THREAD

**Issue by Lyankar** [jverdi/JVFloatLabeledTextField#188]
I'm using story board, I have lot of screens and multiple text fields in each screen. I successfully installed your VFloatLabeledTextField through pod and I imported #import "JVFloatLabeledTextField.h"
#import "JVFloatLabeledTextView.h" files. But I don't know how to use it. Can you please give small example for me....   Ex : firstNameTextField, lasdtNameTextField, ageNameTextField and mobileNumberNameTextField are my textfields in ViewControllerA. I imported #import "JVFloatLabeledTextField.h" #import "JVFloatLabeledTextView.h" files in ViewControllerA successfully. What next.

**Comment by jverdi** [comment]
Please see the example project included in this repo.

https://github.com/jverdi/JVFloatLabeledTextField/blob/master/JVFloatLabeledTextField/JVFloatLabeledTextFieldViewController.m

**Comment by Lyankar** [comment]
Thank u very much
