### ISSUE TITLE
Block warnings XCode 9.3 - Still being maintained?

### ISSUE THREAD

**Issue by RVijay007** [jverdi/JVFloatLabeledTextField#190]
Is this project still being maintained? There seem to be a lot of block warnings on the latest from master with XCode 9.3 (Swift 4.1).

**Comment by Meggapixxel** [comment]
pod 'JVFloatLabeledTextField', :git => 'https://github.com/jverdi/JVFloatLabeledTextField.git', :commit => 'a27d1f5139a8b0e2d247fd80053a7c95a7c30fa5'
