### ISSUE TITLE
crashing on iOS 13 

### ISSUE THREAD

**Issue by JeffWTING** [jverdi/JVFloatLabeledTextField#203]
Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'

**Comment by rheyansh** [comment]
Facing the same issue

**Comment by rheyansh** [comment]
Seems Xcode 11.2 Bug. Upgrade to Xcode 11.2.1 fixed my crash
