### ISSUE TITLE
Version 1.2.2 not available via SPM

### ISSUE THREAD

**Issue by SeanAsby** [jverdi/JVFloatLabeledTextField#212]
When I try to add this to my project via SPM I get this error: 

`https://github.com/jverdi/JVFloatLabeledTextField has no Package.swift manifest for version 1.2.2`

I see that the SPM manifest is added on master but the commit has not been tagged. Maybe you could tag a 1.2.3 version which includes SPM manifest? 

![Screenshot 2020-09-11 at 15 58 56](https://user-images.githubusercontent.com/3429308/92934726-1ed01f00-f448-11ea-9163-62d013ead698.png)
![Screenshot 2020-09-11 at 15 59 04](https://user-images.githubusercontent.com/3429308/92934734-20014c00-f448-11ea-9ba2-1d4353086619.png)
![Screenshot 2020-09-11 at 15 59 27](https://user-images.githubusercontent.com/3429308/92934736-2099e280-f448-11ea-83d5-f58c867b1163.png)

**Comment by eneko** [comment]
@SeanAsby as a workaround, you can select branch `master`

@jverdi would it be possible to tag a 1.2.3 or 1.3.0 release that has Package.swift on it?

**Comment by jverdi** [comment]
@SeanAsby @eneko updated! Looks to be working for me. Please let me know if you run into any issues.

**Comment by SeanAsby** [comment]
Perfect! Thanks!

**Comment by eneko** [comment]
Thank you, @jverdi
