### ISSUE TITLE
Xcode 12 Support

### ISSUE THREAD

**Issue by imediayala** [jverdi/JVFloatLabeledTextField#214]
Minimum deployment target needs to be updated to IOS 9 as apple dropped support for IOS 8 Devices.
Compiler Warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99.

**Comment by iKorich** [comment]
Hey @jverdi   ,

can you update platform version to - platforms: [.iOS(.v9)]? 
or [.iOS(.v11)] to feature

**Comment by jverdi** [comment]
This was updated to 9.

**Comment by iKorich** [comment]
When you’ll tag/release new version ?
