### ISSUE TITLE
JVFloatLabeledTextView unavailable via SPM & Xcode 12.5

### ISSUE THREAD

**Issue by s4cha** [jverdi/JVFloatLabeledTextField#220]
Just updated to Xcode 12.5 and JVFloatLabeledTextField package broke. Seems like `JVFloatLabeledTextView` is unavailable for some reason. Tested on a fresh project as well :)

**Comment by s4cha** [comment]
@tiltem I used it directly by copy pasting the folder for now :)

**Comment by jverdi** [comment]
fixed via #223
