### ISSUE TITLE
textfield doesn't horizontally scroll with the cursor.

### ISSUE THREAD

**Issue by gitHendrix** [jverdi/JVFloatLabeledTextField#67]
If the text is bigger then the visible space the cursor fails to scroll to the right with the text, as the standard behavior does for a UITextField.  Seems like setting the textRectForBounds, stops the UITextField from tracking the cursor.

As I typed it out..
![screen shot 2014-08-11 at 1 29 52 pm](https://cloud.githubusercontent.com/assets/543911/3882382/7181f718-2196-11e4-8f6f-059fd6eea8f9.png)

If press down and scroll to the right of the same text.
![screen shot 2014-08-11 at 1 31 05 pm](https://cloud.githubusercontent.com/assets/543911/3882381/717fbf20-2196-11e4-9cd1-0cd72b967b95.png)

**Comment by mpanoff** [comment]
I'm seeing a similar issue. I believe it has something to do with auto-layout, which I'm using. All input is frozen when text input fills the textField view. Very strange.

**Comment by mpanoff** [comment]
Here's the fix:

```
- (CGRect)textRectForBounds:(CGRect)bounds
{
    CGRect rect = [super textRectForBounds:bounds];
    if ([self.text length] || self.keepBaseline) {
        rect = [self insetRectForBounds:rect];
    }
    return rect;
    //return CGRectIntegral(rect);
}

- (CGRect)editingRectForBounds:(CGRect)bounds
{
    CGRect rect = [super editingRectForBounds:bounds];
    if ([self.text length] || self.keepBaseline) {
        rect = [self insetRectForBounds:rect];
    }
    return rect;
    //return CGRectIntegral(rect);
}
```

**Comment by mpanoff** [comment]
I also removed these lines of code to play nice with auto-layout:

```
//    CGSize floatingLabelSize = [_floatingLabel sizeThatFits:_floatingLabel.superview.bounds.size];
//    
//    _floatingLabel.frame = CGRectMake(_floatingLabel.frame.origin.x,
//                                      _floatingLabel.frame.origin.y,
//                                      floatingLabelfSize.width,
//                                      floatingLabelSize.height);
```

Hope that helps someone. :smile:
