### ISSUE TITLE
Release 1.0.0 broken on iOS 8.1.2

### ISSUE THREAD

**Issue by rsanchezsaez** [jverdi/JVFloatLabeledTextField#81]
It seems that release 1.0.0 messed the vertical positions of the inner textField. Version 0.0.9 was fine.

This is on an iPhone 6 running iOS 8.1.2, building from Xcode 6.2 beta 3 with iOS 7.0 deployment target.

See the following screenshots (first two screenshots are 1.0.0, last two 0.0.9):

![1 0 0 - a](https://cloud.githubusercontent.com/assets/444313/5668449/6e0166e0-9767-11e4-81a0-641cdee62ace.png)
![1 0 0 - b](https://cloud.githubusercontent.com/assets/444313/5668448/6dfe13c8-9767-11e4-84fb-ed6403b2bfb2.png)
![0 0 9 - a](https://cloud.githubusercontent.com/assets/444313/5668446/6df82f58-9767-11e4-93b3-0f8c438ffb65.png)
![0 0 9 - b](https://cloud.githubusercontent.com/assets/444313/5668447/6dfa6bec-9767-11e4-83bd-f3afbe403dfe.png)

**Comment by rsanchezsaez** [comment]
I'm investigating some more.

I'm using AutoLayout, but these `JVFloatLabeledTextField`s I'm showing on the screenshots don't have a defined height constraint, so they are supposed to take height based on their `intrinsicContentSize`. With version 0.0.9, the textFields took a height of 39 points, but with the new version they only end up being 29 points tall (which is guess would be the correct `intrinsicContentSize` for a regular `UITextField`).

I would rather avoid having to manually constraint its height. Do you think something is affecting the `intrinsicContentSize` calculations on 1.0.0?

**Comment by rsanchezsaez** [comment]
Also this is weird: on the new version, the caret is taller even though the typed text size is the same.

**Comment by ammojamo** [comment]
I have this problem too. It is broken in the most basic of AutoLayout senarios.

@jverdi I have set up a sample project here to assist with debugging: https://github.com/ammojamo/LayoutBug

I have narrowed down the issue to changes in the implementation of `- (CGRect)textRectForBounds:(CGRect)bounds`. This method seems to determine the vertical size of the text field as determined by the auto layout engine. This method was changed in 1.0.0 to just return the default UITextField rect when the `text` property is empty - I am not sure what the reasoning for this was so I'm not sure how to fix the issue without potentially breaking something else.

**Comment by rsanchezsaez** [comment]
@ammojamo: Thanks for your research.

As a work-around I have added a height constraint for my `JVFloatLabeledTextField`s for now.

**Comment by jverdi** [comment]
@rsanchezsaez @ammojamo appreciate for the report. I've resorted to specifying an intrinsicContentSize within the text field class for 1.0.1, which seems to resolve the issue for the demo project (thanks for that). Give it a try and let me know if there are any other problems.
