### ISSUE TITLE
Cursor moves downwards when placeholderYPadding is set to a positive value

### ISSUE THREAD

**Issue by fatuhoku** [jverdi/JVFloatLabeledTextField#88]
I want to center my text vertically whilst using `JVFloatLabeledTextView`. To this end, I used the method here http://stackoverflow.com/a/17024644/590767 to offset the `UITextView` appropriately.

I noticed the placeholder stayed towards the top of the text view so I set `placeholderYPadding = 40`.

The placeholder moved. However, this also had the side-effect of offsetting the cursor and of the baseline of the text being typed as well.

You can see the cursor position faintly in the screenie below:

![screen shot 2015-03-26 at 12 34 20](https://cloud.githubusercontent.com/assets/430233/6846809/20c8a7d8-d3b9-11e4-9ec2-7313735e10af.png)

I expected `placeholderYPadding` to have zero effect on the way text is edited on the text view.

**Comment by tailec** [comment]
Can you just center your text vertically setting `placeholderyPadding = textField.bounds.size.height / 2.0 - textField.floatingLabel.font.lineHeight;

**Comment by jverdi** [comment]
See the suggestion above for a possible fix.
