### ISSUE TITLE
Setting label centered text loses alignment

### ISSUE THREAD

**Issue by cytryn** [jverdi/JVFloatLabeledTextField#94]
When I set the text of my label within the viewDidAppear it works fine:
![](https://s3.amazonaws.com/f.cl.ly/items/1P0x3F3x2N052j381H18/Image%202015-05-06%20at%207.55.24%20PM.png)

But when I set it within the viewDidLoad the alignment is left from the center as you can see in the image:
![](http://f.cl.ly/items/2Q0T2E081G2n0q3i0J0o/Image%202015-05-06%20at%207.52.43%20PM.png)

**Comment by jverdi** [comment]
@cytryn I've tried reproducing this in the included ```JVFloatLabeledTextFieldViewController```, but it seems to work fine in both cases. Can you share some code that demonstrates the problem?

**Comment by cytryn** [comment]
Here is a bit of a simple code where the problem is happening:

![](https://s3.amazonaws.com/f.cl.ly/items/2r3q0J2W462r161l3b1a/Image%202015-05-21%20at%202.15.08%20PM.png)

![](https://s3.amazonaws.com/f.cl.ly/items/1b2Q430N0u0V0u333427/Image%202015-05-21%20at%202.18.18%20PM.png)


But the thing is that if I call [self customizeAppearance] in viewDidAppear instead of viewDidLoad, it works.

**Comment by cytryn** [comment]
Apparently version 1.0.3 fixed this, but generated a different bug as described in #98

**Comment by cytryn** [comment]
1.0.4 broke this again apparently...

My placeholder are back in the middle in a strange way just like my previous post.

**Comment by mayankverma** [comment]
After walking through entire code and playing with it, I found this workaround.

Set the "floatingLabelYPadding" property of the textview to 0.
myTextView.floatingLabelYPadding = 0
