### ISSUE TITLE
IB_DESIGNABLE?!

### ISSUE THREAD

**Issue by nvdcmptr** [jverdi/JVFloatLabeledTextField#95]
Hi\
sample could not be compiled.
Error in IB_DESIGNABLE in JVFloatLabeledTextField.h ( unknown type name).

**Comment by jverdi** [comment]
Are you using Xcode 6?

**Comment by nvdcmptr** [comment]
No. Xcode 5.1.1

**Comment by vburojevic** [comment]
I'm getting IB Designables errors as well for latest version (1.0.3) of JVFloatLabeledTextField in Xcode 6.3.1.
Code can compile though.
![screenshot 2015-05-13 16 18 48](https://cloud.githubusercontent.com/assets/2234474/7612571/f910619c-f98b-11e4-850a-67e25ac909de.png)

**Comment by jvanlint** [comment]
I am getting it as well. JVFloat version (1.0.3)
Cocoapods 0.37.1
Xcode 6.3.1

**Comment by walteryaron** [comment]
Same here

**Comment by walteryaron** [comment]
solution
put  use_frameworks!
inside podfile

**Comment by jvanlint** [comment]
can you elaborate a little? What does the podfile line look like now?
or can you post your podfile?

**Comment by jverdi** [comment]
This is indeed an issue with the combination of Cocoapods & static libraries.

Details from Cocoapods can be found here: 
- https://github.com/CocoaPods/CocoaPods/issues/2792
- https://github.com/CocoaPods/CocoaPods/issues/3564

It seems that they would suggest using frameworks as @walteryaron did.

@nvdcmptr @jvanlint let me know if adding ```use_frameworks``` to your Podfile solves the issue for you. 

An example Podfile can be found here: 
http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables/28907253#28907253

https://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang

**Comment by jvanlint** [comment]
It works....but it pollutes the debug console window with a whole heap of messages for each pod installed.

Any news on whether cocoa pods will be addressing this?

**Comment by chlebta** [comment]
I got same issue and each time I open xcode it crash to solve you have to solution : `Update to last version of xcode( released on 18 may)  ` or you use `xcode 6.2`

**Comment by jverdi** [comment]
Carthage is now supported as of version 1.1.0. It can be used as an alternative to Cocoapods. This should make it even easier to adopt JVFloatLabeledTextField as a dynamic iOS 8 framework, which should avoid this IB_DESIGNABLE issue. Please be aware that if you require support for iOS <= 7, this will not be a viable solution.

Installing Carthage:
```
brew update
brew install carthage
```

Create a ```Cartfile``` in your project directory that contains:
```
github "jverdi/JVFloatLabeledTextField"
```

Then run carthage with ```carthage update``` and add ```JVFloatLabeledText.framework``` to your project from the ```Carthage/Build/iOS``` directory.

Finally, include ```JVFloatLabeledText.h``` in your project:
```
#import <JVFloatLabeledText/JVFloatLabeledText.h>
```

Please let me know if there are any issues. 
And thanks to @hartbit for his earlier work on getting this setup.

**Comment by marckaraujo** [comment]
How to make this library works with iOS 7 without use use_frameworks!.... ???

**Comment by WizKIDz** [comment]
Just for reference: i fixed the error show by vburojevic with the following... very odd steps

add use_frameworks! to pod file
pod install
// saw that it gave me a bunch of debug errors so i did the following
removed use_frameworks! from pod file
pod install
// magically fixed the errors mentioned by vburojevic

No idea why or how this fixed it but it did. Hope this might help some people.

**Comment by WizKIDz** [comment]
Dang... it goes back to being an error when you open up the nib that references the JVFloatLabeledTextField 

Shux!

**Comment by jverdi** [comment]
use_frameworks! should no longer be necessary as a result of changes to cocoapods.

**Comment by UmairSharif** [comment]
After adding "user_frameworks!" in podfile it remove the "error: IB Designables: Failed to render instance of JVFloatLabeledTextField: Failed to load designables from path (null)", but another error comes up which is 'JVFloatLabeledTextField.h' file not found. Anyone has idea?
