### ISSUE TITLE
version 1.0.3 will happen this problem

### ISSUE THREAD

**Issue by gtgg** [jverdi/JVFloatLabeledTextField#96]
![ccc](https://cloud.githubusercontent.com/assets/12069397/7645913/afba163c-faee-11e4-8229-7211f4072715.jpg)

**Comment by jverdi** [comment]
Can you describe your use of JVFloatLabeledTextField? Are you providing a tall enough frame to accommodate both?

**Comment by gtgg** [comment]
it work well in version 1.0.0.

**Comment by jverdi** [comment]
Can you provide a code sample/snippet that reproduces the issue?

**Comment by jverdi** [comment]
Closing - please give the latest version a try, and if you are still experiencing this, reopen the issue with steps to reproduce.
