### ISSUE TITLE
Placeholder shrinks after leaving textField

### ISSUE THREAD

**Issue by cytryn** [jverdi/JVFloatLabeledTextField#98]
Just updated to version 1.0.3 and this started to happen...

When I leave the textfield with some text inside, it shrinks the placeholder

![screen shot 2015-05-21 at 5 46 56 pm](https://cloud.githubusercontent.com/assets/735750/7758643/81c24b62-ffe1-11e4-90c0-e6a0b5f61155.png)

No code changes were made by me

**Comment by chanil1218** [comment]
Same here.

**Comment by cytryn** [comment]
I tested 1.0.4 version now and it is still shrinking in some cases after I set the field content and set focus on another text field. It seems its also losing the padding that I previously set on my appDelegate.

![screen shot 2015-05-28 at 12 54 26 pm](https://cloud.githubusercontent.com/assets/735750/7864538/1cad85d6-0539-11e5-94df-10c88094106b.png)


Here is what I have in custom code for the textField class:

![screen shot 2015-05-28 at 12 58 06 pm](https://cloud.githubusercontent.com/assets/735750/7864560/43591f2e-0539-11e5-885e-d418541bda92.png)


And in my app delegate:

![screen shot 2015-05-28 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/735750/7864570/55a28134-0539-11e5-9cd5-8d7e48ebd051.png)
